spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: refrigeratorcleaner@gmail.com
    password: qcpvmzjrnqkouwyr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    database: mysql
    hibernate.ddl-auto: update
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/refrigerator_cleaner?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: kim2580mi

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 558364968188-7ted0ii9d9amnbdictg8v06ipq9mc60r.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope: email, profile

          kakao:
            client-id: fc20ff7d8ebf2289fe8baec9abadb782
            client-secret: DSbzsqGeN5qdEzUVnEW6nv2liSSh2Jdl
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_image, account_email

          naver:
            client-id: iggAieg7YAsZCWBjmHE_
            client-secret: v6oqe5wya3
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: email, profile_image
            client-name: Naver

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

cloud:
  aws:
    s3:
      bucket: refrigerator-cleaner
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIA3IV73HJFRA3CIQVS
      secretKey: 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

jwt:
  secret-key: BOyMEgACzRFOOXpomiqeSvE/rkp12k5WZ81zUOHGTZgPa+k+UkDwS5+nxAD+uz34rsV1C/IUjtz9mWBBzGbDxA==
  access-header: Authorization-Access
  refresh-header: Authorization-Refresh

