spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_PW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    database: mysql
    hibernate.ddl-auto: update
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/refrigerator_cleaner?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PW}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CI}
            client-secret: ${OAUTH_GOOGLE_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope: email, profile

          kakao:
            client-id: ${OAUTH_KAKAO_CI}
            client-secret: ${OAUTH_KAKAO_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_image, account_email

          naver:
            client-id: ${OAUTH_NAVER_CI}
            client-secret: ${OAUTH_NAVER_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: email, profile_image
            client-name: Naver

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PW}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    stack.auto: false
    region.static: ${S3_REGION}
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-header: Authorization-Access
  refresh-header: Authorization-Refresh

default:
  profile: https://naengtul-profile.s3.ap-northeast-2.amazonaws.com/favicon.png

openai:
  model:
    image: dall-e-3
    chat: gpt-3.5-turbo
  api:
    key: ${AI_KEY}
    url:
      chat: https://api.openai.com/v1/chat/completions
      image: https://api.openai.com/v1/images/generations
